resources_storage:
  backend: 'gcs'
  bucket_name: 'pv-prospect-staging'
  prefix: 'resources'

staged_raw_data_storage:
  backend: 'gcs'
  bucket_name: 'pv-prospect-staging'
  prefix: 'raw'

staged_cleaned_data_storage:
  backend: 'gcs'
  bucket_name: 'pv-prospect-staging'
  prefix: 'cleaned'

staged_prepared_batches_data_storage:
  backend: 'gcs'
  bucket_name: 'pv-prospect-staging'
  prefix: 'prepared-batches'

staged_prepared_data_storage:
  backend: 'gcs'
  bucket_name: 'pv-prospect-staging'
  prefix: 'prepared'

versioned_raw_data_storage:
  backend: 'gcs'
  bucket_name: 'pv-prospect-versioned-raw'

versioned_feature_data_storage:
  backend: 'gcs'
  bucket_name: 'pv-prospect-versioned-feature'
