@startuml

!include theme.puml


collections "Third Party APIs" as ThirdPartyAPIs

database Staging {
  database "Resources" as StagingResources
  database "Raw" as StagingRaw
  database "Cleaned" as StagingCleaned
  database "Prepared" as StagingPrepared
}

database "Versioned Raw Data" as VersionedRaw
database "Versioned Feature Store" as VersionedFeature

database "Versioned Model Store" as VersionedModel

component "Model Trainer" as ModelTrainer

component "Data Extractor" as DataExtractor
component "Data Transformer" as DataTransformer
component "Data Versioner" as DataVersioner
database "Project Instance Repo" as ProjectInstanceRepo #transparent

component "PV Prospect App" as PvProspectApp {
  component "Prediction API" as PredictionApi
  component "Weather Model" as WeatherModel
  component "PV Model" as PvModel
  ' Roadmap (not yet implemented):
  component "Validation API <<roadmap>>" as ValidationApi
  component "In-Memory Data <<roadmap>>" as InMemoryData
}

actor User


User --> PredictionApi : lat, lon, period

PredictionApi --> WeatherModel : DNI, DHI, \ntemperature = \ncall_model(\nlat, lon, \nday, year)
PredictionApi <- PredictionApi : calculate_POA
PredictionApi --> PvModel : predicted\nenergy \nyield = \ncall_model(\nPOA, \ntemperature)

' Roadmap flows (not yet implemented):
User --> ValidationApi #lightgray
ValidationApi --> PvModel #lightgray
ValidationApi --> InMemoryData #lightgray
InMemoryData <--- DataVersioner #lightgray

ThirdPartyAPIs <-- DataExtractor : E2: call

StagingResources <-- DataExtractor: E1: get
DataExtractor --> StagingRaw : E3: put

DataTransformer --> StagingResources : C1: get
DataTransformer --> StagingRaw : C2: get
DataTransformer --> StagingCleaned : C3: put\nP1: get
DataTransformer <- DataTransformer : P2: calculate_POA
DataTransformer --> StagingPrepared : P3: put
StagingCleaned -[hidden]> StagingPrepared

component "Data Transformer" as DataTransformer

StagingRaw <-- DataVersioner : V1: get
VersionedRaw <- DataVersioner : V2: push (using DVC)

StagingPrepared <-- DataVersioner : V3: get
VersionedFeature <-- DataVersioner : V4: push (using DVC)
DataVersioner -> ProjectInstanceRepo : V5: tag data-v<date>

VersionedFeature <-- ModelTrainer : M1: pull (dvc)
VersionedModel <-- ModelTrainer : M2: push promoted\nartifacts (DVC +\nplain serving path)
ProjectInstanceRepo <- ModelTrainer : M3: tag model-v<date>

PvProspectApp ---> VersionedModel : A1: load promoted\nartifacts at startup

@enduml
