@startuml

!include theme.puml

collections "Third Party APIs" as ThirdPartyAPIs

database "Staging" as Staging {
  database "Resources" as StagingResources
  database "Raw" as StagingRaw
  database "Cleaned" as StagingCleaned
  database "Prepared" as StagingPrepared
}

database "Versioned Raw Data" as VersionedRawData
database "Versioned Model Data" as VersionedModelData

component "Data Extractor" as DataExtractor
component "Data Transformer" as DataTransformer

component Models {
  component "Weather Model" as WeatherModel
  component "PV Model" as PvModel
}

component "Model Trainer" as ModelTrainer

component "PV Prospect App" as PvProspectApp {
  component "Prediction API" as PredictionApi
  component "Validation API" as ValidationApi
'  component "Irradiance Calculator" as IrradianceCalculator
  component "In-Memory Data" as InMemoryData
}

component "Data Versioner" as DataVersioner
database "Project Instance Repo" as ProjectInstanceRepo #transparent

actor User


User --> ValidationApi
User --> PredictionApi : lat, lon, period

PredictionApi ---> WeatherModel : DNI, DHI, \ntemperature = \ncall_model(\nlat, lon, \nday, year)
PredictionApi <- PredictionApi : calculate_POA
PredictionApi ----> PvModel : predicted\nenergy \nyield = \ncall_model(\nPOA, \ntemperature)

ValidationApi --> PvModel : predicted\nenergy\nyield = \ncall_model(\nPOA, \ntemperature, \nsite ID)
ValidationApi --> InMemoryData : get_actual_energy_yield()

VersionedModelData <-- ModelTrainer : M1: pull
Models <-- ModelTrainer : M2: train

ThirdPartyAPIs <-- DataExtractor : E2: call

StagingResources <-- DataExtractor: E1: get
DataExtractor --> StagingRaw : E3: put

DataTransformer --> StagingResources : C1: get
DataTransformer --> StagingRaw : C2: get
DataTransformer --> StagingCleaned : C3: put\nP1: get
DataTransformer <- DataTransformer : P2: calculate_POA
DataTransformer --> StagingPrepared : P3: put
StagingCleaned -[hidden]> StagingPrepared

InMemoryData <--- DataTransformer : P3: put

StagingRaw <-- DataVersioner : V1: get
VersionedRawData <- DataVersioner : V2: push (using DVC)

StagingPrepared <-- DataVersioner : V3: get
VersionedModelData <-- DataVersioner : V4: push (using DVC)
DataVersioner -> ProjectInstanceRepo : V5: push (using Git)

InMemoryData ---> VersionedModelData : A1: pull
InMemoryData ---> StagingPrepared : A2: get

@enduml
