@startuml

!include theme.puml

skinparam nodesep 60
skinparam ranksep 90
skinparam rankdir TB

collections "Third Party APIs" as ThirdPartyAPIs

database "Raw Data" as RawData

database Staging {
'  database "Resources" as StagingResources
'  database "Data" as StagingData {
    database "Cleaned" as StagingCleaned
    database "Prepared" as StagingPrepared
    database "Served" as StagingServed
'  }
}

database "Versioned Feature Store" as VersionedFeature

database "Versioned Model Store" as VersionedModel

component "Model Trainer" as ModelTrainer

component "Data Extractor" as DataExtractor
component "Data Transformer" as DataTransformer
component "Data Versioner" as DataVersioner
database "Project Instance Repo" as ProjectInstanceRepo #transparent

component "PV Prospect App" as PvProspectApp

actor User

'DataExtractor -[hidden]> DataTransformer

RawData -[hidden]> Staging

StagingCleaned -[hidden]> StagingPrepared
RawData -[hidden]> StagingCleaned
StagingPrepared -[hidden]> StagingServed

'PvProspectApp --> StagingResources : D0: get
PvProspectApp --> VersionedModel : D1: get
PvProspectApp --> StagingServed : D2: get

'DataExtractor ---> StagingResources : A0: get
'ThirdPartyAPIs <- DataExtractor : A1: call
ThirdPartyAPIs <-- DataExtractor : A1: call
DataExtractor --> RawData : A2: put

'DataTransformer --> StagingResources : B1: get
DataTransformer --> RawData : B1: get
DataTransformer --> StagingCleaned : B2: put\nC1: get

DataTransformer <- DataTransformer : C2: calculate_POA
DataTransformer --> StagingPrepared : C3: put
DataTransformer --> StagingServed : C4: put

StagingPrepared <-- DataVersioner : E1: get
VersionedFeature <-- DataVersioner : E2: push (dvc)
DataVersioner -> ProjectInstanceRepo : E3: tag data-v<date>

VersionedFeature <-- ModelTrainer : F1: pull (dvc)
VersionedModel <-- ModelTrainer : F2: push (dvc)
ProjectInstanceRepo <- ModelTrainer : F3: tag model-v<date>

User --> PvProspectApp


@enduml
